version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-fiko
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: "mysql-fiko"
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  php:
    restart: always
    build:
      context: .
      target: php1
      # dockerfile: Dockerfile
    container_name: php-fiko
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - server
  server:
    build:
      context: .
      target: golang1
    container_name: go-server
    ports:
      - 8888:8888
    volumes:
      - ./src/server:/usr/src/server
    command: air src/server/main.go -b 0.0.0.0
    networks:
      - laravel
